### ISSUE TITLE
Package Name Issue on Android

### ISSUE THREAD

**Issue by aaronksaunders** [lewebsimple/vue-cli-template#2]
If you use the default values for creating you android app, everything works fine, but if you change application id from the default; 
```
? Project name pascalapp-vue
? Application ID com.clearlyinnovative.pascalapp
? Project description NativeScript-Vue application
? Project version 1.0.0
? Author Aaron Saunders <aaron@clearlyinnovative.com>
? License MIT
```

you app will not load

`ActivityManager: Invalid packageName: com.clearlyinnovative.pascalapp`

**Comment by lewebsimple** [comment]
It's related to the '-' in the project name.
It's fixed in the official repo here: https://github.com/nativescript-vue/vue-cli-template
